version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:15.11.0
    working_directory: ~/claim-dapp
    resource_class: medium+
    steps:
      - checkout
      - run:
          name: Run build
          command: |
            yarn
            yarn build
      - save_cache:
          key: claim-dapp-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/claim-dapp
  test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/claim-dapp
    steps:
      - restore_cache:
          key: claim-dapp-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run tests
          command: yarn test --watchAll=false

workflows:
  version: 2.1
  claim-test:
    jobs:
      - build
      - test:
          requires:
            - build
